name: CI

on:
  pull_request:
    branches:
      - main
      - sv2-integration-braidpool
  push:
    branches:
      - main
      - sv2-integration-braidpool

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    env:
      CARGO_TARGET_DIR: ${{ github.workspace }}/target
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install capnp dependencies
        run: sudo apt-get install -y capnproto libcapnp-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.88
        with:
          components: clippy

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: "false"
          key: cargo-inputs-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
          workspaces: integration-tests -> ../target

      - name: Clippy check (braidpool crates)
        run: |
          cargo clippy --manifest-path=pool-apps/Cargo.toml -p braidpool-common -p braidpool-template-provider -- -D warnings

  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install capnp dependencies
        run: sudo apt-get install -y capnproto libcapnp-dev

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check formatting (braidpool crates)
        run: |
          cargo fmt -p braidpool-common -p braidpool-template-provider --manifest-path=pool-apps/Cargo.toml -- --check

  machete:
    name: Unused Dependencies (cargo machete)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-machete
        run: cargo install cargo-machete --locked
      - name: Run cargo-machete (braidpool crates)
        run: |
          cargo machete pool-apps/braidpool-common
          cargo machete pool-apps/braidpool-template-provider
